const productsData = [
    {
      id: 1,
      name: "Lali",
      date: "4 de marzo",
      time: "20:00 pm",
      category: "conciertos",
      cardImg: "./img/imgProduct/Lali3DIC600.jpg",
    },
    {
        id: 2,
        name: "Camilo",
        date: "16 de marzo",
        time: "21:00 pm",
        category: "conciertos",
        cardImg: "./img/imgProduct/Camilo.jpg",
      },
      {
        id: 3,
        name: "David Guetta",
        date: "9 de febrero",
        time: "20:30 pm",
        category: "conciertos",
        cardImg: "./img/imgProduct/davidguetta.jpg",
      },
      {
        id: 4,
        name: "Alejandro Sanz",
        date: "21 de enero",
        time: "20:00 pm",
        category: "conciertos",
        cardImg: "./img/imgProduct/Sanz.jpg",
      },
      {
        id: 5,
        name: "Reik",
        date: "6 de marzo",
        time: "20:00 pm",
        category: "conciertos",
        cardImg: "./img/imgProduct/Reik.jpg",
      },
      {
        id: 6,
        name: "Connie Ballarini",
        date: "14 de febrero",
        time: "21:30 pm",
        category: "teatro",
        cardImg: "./img/imgProduct/connie.jpg",
      },
      {
        id: 7,
        name: "La Granja",
        date: "6 de marzo",
        time: "17:00 pm",
        category: "teatro",
        cardImg: "./img/imgProduct/lagranja.jpg",
      },
];